chmod on joblog.txt

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -162,14 +162,14 @@ jobs:
       - name: Print tests that are going to be run in this chunk
         run: cat tests_chunk_${{ matrix.chunk_number }}
 
-      # Run a selected chunk of tests in parallel, keep a log; on error, print out said log w/ failure
-      # summaries at the bottom
+      # Run a selected chunk of tests in parallel, keep a log; on error, print out said log. 
+      # Lastly, make log readable for awk in next step
       - name: Run tests
         run: >-
           cat tests_chunk_${{ matrix.chunk_number }}
           | sort
           | parallel --timeout 600 --group --joblog joblog.txt
-          || { cat joblog.txt && awk '/FAILURES/,/short/' joblog.txt && exit 1; }
+          || { cat joblog.txt && chmod a=r joblog.txt && exit 1; }
         env:
           # Map secrets to environment variables
           MC_BRANDWATCH_PASSWORD: ${{ secrets.MC_BRANDWATCH_PASSWORD }}
@@ -188,3 +188,6 @@ jobs:
           MC_TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.MC_TWITTER_ACCESS_TOKEN_SECRET }}
           MC_TWITTER_CONSUMER_KEY: ${{ secrets.MC_TWITTER_CONSUMER_KEY }}
           MC_TWITTER_CONSUMER_SECRET: ${{ secrets.MC_TWITTER_CONSUMER_SECRET }}
+      
+      - name: Print test failures
+        run: awk '/FAILURES/,/short/' joblog.txt
