Run a bunch of sample tests

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -17,6 +17,9 @@ jobs:
         with:
           submodules: recursive
 
-      - name: Try setting some annotations
-        run: |
-          echo "::error file=app.js,line=10,col=15::The quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThe quick brown fox jumps over the lazy dog%0AThis is the final line"
+      - name: Run sample tests
+        run: >-
+          cat .github/sample-tests/list.txt
+          | parallel --group --joblog joblog.txt
+          || { cat joblog.txt && exit 1; }
+        #   echo "::error file=app.js,line=10,col=15::First line%0ASecond line%0AThird line"
